name: Test Build (Ubuntu)

on:
  pull_request:
    branches: [aaroads]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      # Node v18.17.0, introduced July 18, 2023, introduces an error in unicode processing that breaks test cases on Ubuntu.
      # See PR #905 and #908 for more details.
      # If this bug is resolved in node, these lines can revert to 18.x rather than 18.16.1.
      - name: Use Node.js 18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: Build Shield Library 🛡️
        run: |
          cd shieldlib
          npm ci --include=dev
          npm run build
      - name: Install and Build 🔧
        run: |
          npm ci --include=dev
          npm run build
          npm run style
      - name: Test 🧪
        run: |
          npm test
          cd shieldlib
          npm test
